### ISSUE TITLE
Lazy load images

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/foed#39]
All images should be loaded lazily (only when they're in screen) with some kind of fancy React package.

- Lightweight
- No intersection observer due to poor browser support
- TypeScript support is a plus
- Simple API

https://github.com/jasonslyvia/react-lazyload 11.1kb minified
https://github.com/loktar00/react-lazy-load 10.3kb minified
https://github.com/sergiodxa/react-lazy-image
~https://github.com/Merri/react-lazy~
~https://github.com/FormidableLabs/react-progressive-image~
~https://github.com/mbrevda/react-image~

**Comment by RogerKemp** [comment]
Nice fade in as well please.
