### ISSUE TITLE
Background color inconsistent

### ISSUE THREAD

**Issue by RogerKemp** [Volst/foed#51]
Behind the title element, there is a solid background color, covering the gradient background color. It shouldn't show this solid.

![img_dbe3e595ef7d-1](https://user-images.githubusercontent.com/4288027/41345160-29a6f13c-6f03-11e8-9ec6-326d2d05f9ac.jpeg)

**Comment by SpaceK33z** [comment]
I know, this is almost impossible to fix if we don't want to use a scrollbox (instead of scrolling on body).

**Comment by RogerKemp** [comment]
I have no ide what you are saying, but can't you give the body a background gradient and that's it?

**Comment by RogerKemp** [comment]
Oh the sticky tricky nav...

**Comment by RogerKemp** [comment]
But what if you made the the background fixed, then give the sticky nav a background when it's sticky?
