### ISSUE TITLE
Restaurant/organization image jumping

### ISSUE THREAD

**Issue by RogerKemp** [Volst/foed#57]
Issue:
While loading screens with images it takes a while for the images to load.

Expected result:
Instantly loading of images, since they are small and few.

Issue:
Jumping of images while loading and rendering.

Expected result:
Since the dimensions of the images are known, there should be a placeholder dimension which prevents "jumping" of images and content.

**Comment by Rutger** [comment]
This happens because of wrapping text on the right of it. Will fix.
