### ISSUE TITLE
Design navigation for restaurant app

### ISSUE THREAD

**Issue by SpaceK33z** [Volst/foed#69]
We need either a top bar or a bottom bar.

From #64:

> A hamburger menu has gotten out of fashion, and for a good reason. I'd like some kind of topbar or bottombar navigation.
> A user can be a part of multiple restaurants. So they would first need to select the restaurant they want to complete orders from. If the user has only one restaurant, they'd be redirected immediately to the order page for that one restaurant (it wouldn't make sense to display a list of one restaurant). Does this make sense?

**Comment by SpaceK33z** [comment]
@Rutger can this be closed?

**Comment by Rutger** [comment]
yes
