### ISSUE TITLE
Add menu item on enter instead of save

### ISSUE THREAD

**Issue by Rutger** [Volst/foed#70]
In the admin app, if you want to add an item and press Enter, you expect the item to be added. 
Instead, the interface saves the view unexpectedly.

![screen shot 2018-08-01 at 16 24 04](https://user-images.githubusercontent.com/6998113/43527630-5a717844-95a7-11e8-8244-7086aa96c16a.png)

**Comment by SpaceK33z** [comment]
Would it make sense to always disable saving the form with <kbd>enter</kbd>?

**Comment by Rutger** [comment]
Not when it's a short form like logins, but with long/custom forms, yes.
