### ISSUE TITLE
Merge identical orders in restaurant receipt

### ISSUE THREAD

**Issue by Rutger** [Volst/foed#82]
![screen shot 2018-08-16 at 15 11 07](https://user-images.githubusercontent.com/6998113/44210461-d65dae80-a166-11e8-94d7-626300374593.png)

It's hard to see how many orders should be completed, so it should be like this:

<img width="395" alt="screen shot 2018-08-16 at 15 13 22" src="https://user-images.githubusercontent.com/6998113/44210493-ee353280-a166-11e8-94df-47ab658d01f4.png">

I'll create the styles, but could you make the logic first?
The plus and minus buttons should be able to add or remove completed items.

I also need some kind of state on the receipt when all items are completed. The `Notify Customer` button will light up when that happens.

**Comment by Rutger** [comment]
Okay we changed the idea:
We discarded the `1 out of 4`-part.

We need to merge identical orders, while being able to mark them done all at once. You should also be able to cancel the `done`-mark.

![44210461-d65dae80-a166-11e8-94d7-626300374593](https://user-images.githubusercontent.com/6998113/44257022-1e361180-a20b-11e8-96d1-a64a76d62d82.png)
would become this:
![screen shot 2018-08-17 at 10 47 48](https://user-images.githubusercontent.com/6998113/44257082-49206580-a20b-11e8-9d10-ec542f02f3f9.png)


You should also be able to Notify a customer multiple times. When all items are marked as done, the slider would say `Notify as completed`, which would complete the order.

**Comment by RogerKemp** [comment]
You still need the order details though, right? Or should I not look at the acutal list in the last mock ups?

**Comment by Rutger** [comment]
> You still need the order details though, right?

Only the orange details, yes. You don't need the price and stuff right?

**Comment by RogerKemp** [comment]
Not sure - we'll ask when we meet the reastaurant guy. For now I think the interaction is more important than the content details.
