### ISSUE TITLE
Fix menu variations price display

### ISSUE THREAD

**Issue by Rutger** [Volst/foed#91]
![screen shot 2018-09-03 at 16 42 47](https://user-images.githubusercontent.com/6998113/44992740-72295000-af98-11e8-8020-45798d91f9cd.png)

**Comment by Rutger** [comment]
I feel like the cleanest way to do this would be to change the `Item`-type and add a getter that returns the price including options. Not sure how to do this tho.

**Comment by SpaceK33z** [comment]
Can you describe what the actual and expected result is? No idea what to do

**Comment by Rutger** [comment]
Toppings and variations aren't included in the price of the receipt.

![screen shot 2018-09-03 at 16 56 43](https://user-images.githubusercontent.com/6998113/44993330-79e9f400-af9a-11e8-8a43-7f62715ff2df.png)

The total of this selection will only be €5,95. However it will include the price of options and variations in the subtotal. I would expect the receipt to show €9,70 when this selection is made.
